coverage:
  status:
    project:
      default:
        # `auto` compares coverage with the base-commit
        target: auto

    patch:
      default:
        target:auto

comment:
  layout: "header, reach, diff, flags, files"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes
  show_carryforward_flags: yes

flag_management:
  default_rules:
    carryforward: false
    statuses:
      - type: project
        target: auto
      - type: patch
        target: auto
  individual_flags:
    - name: keras_core
      paths:
        - keras_core
    - name: keras_core.applications
      paths:
        - keras_core/applications
      carryforward: true
