[tool.black]
line-length = 80

# black needs this to be a regex
# to add more exclude expressions
# append `| <regex-expr>` (e.g. `| .*_test\\.py`) to this list
extend-exclude = """
(
  examples/
)
"""

[tool.isort]
profile = "black"
force_single_line = "True"
known_first_party = ["keras_core", "tests"]
default_section = "THIRDPARTY"
line_length = 80
extend_skip_glob=["examples/*", "guides/*"]
